config/routes.rb
# typed: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"


  namespace :receptionists do
    get "dashboard", to: "dashboard#index", as: :root
    get "patients", to: "dashboard#index", as: :patients

    resources :patients
  end
  namespace :doctors do
    get "dashboard", to: "dashboard#index", as: :root

    resources :patients, only: [ :show ]
  end

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doctor.rb
# typed: true

class Doctor < User
end

app/models/patient.rb
# typed: true

class Patient < ApplicationRecord
  belongs_to :receptionist, class_name: "Receptionist"

  validates :full_name, presence: true
  validates :phone, numericality: true, length: { is: 10 }, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true, presence: true
  validates :date_of_birth, presence: true
  validate :date_of_birth_validation
  validates :gender, inclusion: { in: %w[male female other] }, presence: true


  def age
    return nil unless date_of_birth
    now = Date.today

    now.year - date_of_birth.year - ((now.month > date_of_birth.month || (now.month == date_of_birth.month && now.day >= date_of_birth.day)) ? 0 : 1)
  end

  def registered_by
    receptionist&.full_name || "Unknown"
  end

  private

  def date_of_birth_validation
    if date_of_birth.present? && date_of_birth > Date.today
      errors.add(:date_of_birth, "can't be in the future")
    end
  end
end

app/models/receptionist.rb
class Receptionist < User
  has_many :patients, class_name: "Patient", foreign_key: "receptionist_id"
end

app/models/user.rb
# typed: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :full_name, presence: true
  validates :type, presence: true

  def doctor?
    is_a?(Doctor)
  end

  def receptionist?
    is_a?(Receptionist)
  end
end

app/controllers/application_controller.rb
# typed: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:full_name, :email, :type, :password, :password_confirmation) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:full_name, :email, :current_password, :password, :password_confirmation) }
  end

  def after_sign_in_path_for(resource)
    case resource
    when Receptionist
      receptionists_root_path
    when Doctor
      doctors_root_path
    else
      root_path
    end
  end

  def authorize_receptionist!
    unless current_user&.receptionist?
      flash[:alert] = "Not authorized."
      redirect_to root_path
    end
  end

  def authorize_doctor!
    unless current_user&.doctor?
      flash[:alert] = "Not authorized."
      redirect_to root_path
    end
  end
end

app/controllers/doctors/dashboard_controller.rb
class Doctors::DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_doctor!

  def index
    @patients = Patient.where(created_at: (Time.current.beginning_of_day..Time.current.end_of_day)).includes(:receptionist)
    # @patients_chart = Patient.group_by_day(:created_at, range: 30.days.ago..Time.zone.now).count
    @patients_chart = Patient.group_by_day(:created_at).count
  end
end

app/controllers/doctors/patients_controller.rb
class Doctors::PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_doctor!

  def show
    @patient = Patient.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/receptionists/dashboard_controller.rb
class Receptionists::DashboardController < ApplicationController
  before_action :authorize_receptionist!

  def index
    @patients = current_user.patients.order(created_at: :desc)
  end
end

app/controllers/receptionists/patients_controller.rb
# typed: true

class Receptionists::PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_receptionist!
  before_action :set_patient, only: [ :show, :edit, :update, :destroy ]



  def show
  end

  def new
    @patient = current_user.patients.new
  end

  def create
    @patient = current_user.patients.new(patient_params)
    if @patient.save
      redirect_to receptionists_patient_path(@patient), notice: "Patient was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
      redirect_to receptionists_patient_path(@patient), notice: "Patient was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @patient.destroy

    redirect_to receptionists_patients_path, notice: "Patient was successfully destroyed."
  end

  private
    def set_patient
      @patient = current_user.patients.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:full_name, :date_of_birth, :gender, :address, :phone, :email, :medical_issues)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors/dashboard_helper.rb
module Doctors::DashboardHelper
end

app/helpers/doctors/patients_helper.rb
module Doctors::PatientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/receptionists/dashboard_helper.rb
module Receptionists::DashboardHelper
end

app/helpers/receptionists/patients_helper.rb
module Receptionists::PatientsHelper
end

app/views/doctors/dashboard/index.html.erb
<div class="max-w-6xl mx-auto py-8 px-4">
  <h1 class="text-2xl font-bold mb-4">Welcome, <%= current_user.full_name %></h1>

<% if @patients.any? %>
<div class="bg-white shadow-md rounded-lg p-6">
    <h2 class="text-xl font-semibold text-gray-800 mb-4">Patients Registered Today: <%= @patients.count %></h2>

  <div class="overflow-x-auto">
     <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Age</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Registered By</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
         <tbody class="bg-white divide-y divide-gray-200">
              <% @patients.each do |patient| %>
                <tr>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"><%= patient.full_name %></td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"><%= patient.age %></td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"><%= patient.registered_by %></td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm">
                    <%= link_to "View", doctors_patient_path(patient), class: "text-indigo-600 hover:text-indigo-900 font-medium cursor-pointer" %>
                  </td>
                </tr>
              <% end %>
        </tbody>
    </table>
    <% else %>
    <div class="bg-white text-center shadow p-6 rounded-lg">
        <p class="text-gray-600 text-lg">No patients have been registered today.</p>
      </div>
    <% end %>

    

    <div class="mt-8 bg-white p-6 rounded-lg shadow">
      <h3 class="text-lg font-font-semibold text-gray-800 mb-4">Patient Registrations Over Time</h3>
      <%= line_chart @patients_chart, height: "300px", library: {
        backgroundColor: "transparent",
        title: { display: true, text: "Patients per Day", font: { size: 18 } },
        legend: { display: false }
      } %>
    </div>

</div>




    <%# <canvas id="patientChart" width="400" height="200"></canvas>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const ctx = document.getElementById('patientChart');
            const chart = new Chart(ctx, {
                data: {
                    datasets: [{
                        type: 'line',
                        label: 'Patients Registered',
                        data: < %= raw @patient_counts.values.to_json % > ,
                        borderColor: 'rgb(75, 192, 192)',
                        tension: 0.2
                    }, {
                        type: 'bar',
                        label: 'Patients Registered',
                        data: < %= raw @patient_counts.values.to_json % > ,
                        borderColor: 'rgb(75, 192, 192)',
                        tension: 0.2
                    }],
                    labels: < %= raw @patient_counts.keys.to_json % > ,
                }
            })
        })
    </script> %>

app/views/doctors/patients/show.html.erb
<h1 class="text-xl font-bold mb-4">Patient Details</h1>

<p><strong>Full Name:</strong> <%= @patient.full_name %></p>
<p><strong>Email:</strong> <%= @patient.email %></p>
<p><strong>Phone:</strong> <%= @patient.phone %></p>
<p><strong>Date of Birth:</strong> <%= @patient.date_of_birth %></p>
<p><strong>Gender:</strong> <%= @patient.gender %></p>
<p><strong>Address:</strong> <%= @patient.address %></p>
<p><strong>Medical Issues:</strong> <%= @patient.medical_issues %></p>

<%= link_to "Back to Dashboard", doctors_root_path %>

app/views/home/index.html.erb
<%# <%= render 'shared/navbar' %>

    <div class="h-[80vh] bg-gray-50 flex flex-col items-center justify-center text-center px-4">
        <h1 class="text-4xl md:text-5xl font-bold text-blue-600 mb-4">Clinic Portal</h1>
        <p class="text-gray-600 text-lg mb-8">A simple patient portal for Receptionists and Doctors.</p>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Clinic Portal" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%# <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %> 
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="bg-gray-100 min-h-screen max-w-7xl mx-auto">
   

    <%= render "shared/navbar" %>
    
       <%# <p class="notice"><%= notice </p>
       <p class="alert"><%= alert </p> %>
    
    <main class="container min-h-[80vh] mx-auto px-4 py-6">
      <%= render "shared/flash" %>

      <%= yield %>
    </main>

    <%= render "shared/footer" %> 
    <%# <%= turbo_frame_tag :modal %>
  </body>
</html>

app/views/receptionists/dashboard/index.html.erb
<div class="max-w-6xl mx-auto py-8 px-4">
  <h1 class="text-2xl font-bold mb-6">Receptionist: <%= current_user.full_name %></h1>

  <div class="flex justify-between items-center mb-4">
    <h2 class="text-lg font-semibold">Your Patients</h2>
    
    <%= link_to "New Patient", new_receptionists_patient_path,
    class: "bg-indigo-600 text-white px-4 py-2 rounded hover:bg-indigo-700 inline-block" %>
         </div>

    <%= render "receptionists/patients/list", patients: @patients %>

  </div>

app/views/receptionists/patients/_form.html.erb
<%= form_with model: [:receptionists, @patient], data: { turbo_frame: "_top" }, class: "space-y-4" do |f| %>
<% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>
      <ul><% patient.errors.full_messages.each { |msg| concat(content_tag(:li, msg)) } %></ul>
    </div>
  <% end %>

<div>
    <%= f.label :full_name, class: "block text-sm font-medium text-gray-700" %>
    <%= f.text_field :full_name, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %><br />
</div>
    <div><%= f.label :phone, class: "block text-sm font-medium text-gray-700" %>
    <%= f.text_field :phone, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %><br />
</div>

    <div><%= f.label :email, class: "block text-sm font-medium text-gray-700" %>
    <%= f.text_field :email, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %><br />
</div>

    <div><%= f.label :date_of_birth, class: "block text-sm font-medium text-gray-700" %>
    <%= f.date_field :date_of_birth, as: :date, max: Date.today.strftime("%Y-%m-%d"), class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %><br />
</div>

    <div><%= f.label :gender, class: "block text-sm font-medium text-gray-700" %>
    <%= f.select :gender, [["Male", "male"], ["Female", "female"], ["Other", "other"]], { include_blank: 'Select gender' }, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"  %><br />
</div>

    <div><%= f.label :address, class: "block text-sm font-medium text-gray-700" %>
    <%= f.text_area :address, rows: 3, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %><br />
</div>

    <div><%= f.label :medical_issues, class: "block text-sm font-medium text-gray-700" %>
    <%= f.text_area :address, rows: 3, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %><br />
</div>

    <div class="flex justify-end gap-6">

        <button data-action="click->modal#close" class="inline-flex justify-center py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50">Close</button>

        <%= f.submit class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700" %>
</div>
<% end %>

app/views/receptionists/patients/_list.html.erb
<% if @patients.any? %>
   <div class="overflow-x-auto bg-white shadow rounded">
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-100">
          <tr>
            <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Full Name</th>
      <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Date of Birth</th>
      <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Phone</th>
      <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700">Email</th>
      <th class="px-6 py-3 text-left text-sm font-semibold text-gray-700" colspan="3">Actions</th>
</tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <%= render partial: "receptionists/patients/patient", collection: @patients %>
        </tbody>
      </table>
    </div>
    <% else %>
      <p class="text-gray-600 mt-4">No patients registered today.</p>
    <% end %>

app/views/receptionists/patients/_patient.html.erb
<tr id="<%= dom_id(patient) %>">
          <td class="px-6 py-4"><%= patient.full_name %></td>
          <td class="px-6 py-4"><%= patient.date_of_birth %></td>
          <td class="px-6 py-4"><%= patient.phone %></td>
          <td class="px-6 py-4"><%= patient.email %></td>
          <td class="inline-flex pt-2">
            
            <%= link_to "Show", receptionists_patient_path(patient), data: { turbo: false }, class: "px-4 text-indigo-600 hover:text-indigo-900" %> | 
                  <%= link_to "Edit", edit_receptionists_patient_path(patient), data: { turbo: false }, class: "px-4 text-blue-600 hover:text-blue-700" %> |
                  <%= button_to "Delete", receptionists_patient_path(patient),
        method: :delete,
        form: { data: { turbo_confirm: "Are you sure you want to delete this patient?" } },
        class: "px-4 text-red-600 hover:text-red-700" %>
            </td>
        </tr>

app/views/receptionists/patients/edit.html.erb
<div class="p-6 relative max-w-lg mx-auto">
  <p  class="inline-flex items-center text-sm font-medium gap-2 text-indigo-600 mb-4"> <%= icon "arrow-left", class: "w-4 h-4" %> <%= link_to "Back to All Patients", receptionists_patients_path %></p>

<div class="bg-white shadow-lg rounded-lg p-6 relative max-w-lg mx-auto">
    <h2 class="text-lg font-semibold mb-4">Edit Patient</h2>
    <%= render "form", patient: @patient %>
</div>

app/views/receptionists/patients/new.html.erb
<div class="p-6 relative max-w-lg mx-auto">
  <p  class="inline-flex items-center text-sm font-medium gap-2 text-indigo-600 mb-4"> <%= icon "arrow-left", class: "w-4 h-4" %> <%= link_to "Back to All Patients", receptionists_patients_path %></p>

<div class="bg-white shadow-lg rounded-lg p-6 relative max-w-lg mx-auto">
    <h2 class="text-lg font-semibold mb-4">New Patient</h2>
    <%= render "form", patient: @patient %>
</div>

app/views/receptionists/patients/show.html.erb
<div class="max-w-3xl mx-auto bg-white p-6 rounded shadow mt-6">
  <h2 class="text-2xl font-semibold text-gray-800 mb-4">Patient Details</h2>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-gray-700">
    <div><strong>Full Name:</strong> <%= @patient.full_name %></div>
    <div><strong>Email:</strong> <%= @patient.email %></div>
    <div><strong>Phone:</strong> <%= @patient.phone %></div>
    <div><strong>Date of Birth:</strong> <%= @patient.date_of_birth %></div>
    <div><strong>Gender:</strong> <%= @patient.gender %></div>
    <div><strong>Address:</strong> <%= @patient.address %></div>
    <div class="md:col-span-2">
      <strong>Medical Issues:</strong>
      <p class="mt-1"><%= @patient.medical_issues %></p>
    </div>
  </div>

  <div class="flex items-center justify-start gap-4 mt-6">
    <%= link_to "Edit", edit_receptionists_patient_path(@patient),
        class: "inline-block px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700" %>

    <%= link_to "Back to All Patients", receptionists_patients_path,
        class: "inline-block px-4 py-2 bg-gray-200 text-gray-800 rounded hover:bg-gray-300" %>

    <%= button_to "Delete", receptionists_patient_path(@patient),
        method: :delete,
        form: { data: { turbo_confirm: "Are you sure you want to delete this patient?" } },
        class: "inline-block px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700" %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="mb-4 px-4 py-2 rounded text-white 
              <%= key == 'notice' ? 'bg-green-500' : 'bg-red-500' %>">
    <%= value %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-white border-t text-center py-4 text-sm text-gray-500 mt-8">
  <div class="container mx-auto">
     Built with Ruby on Rails by <a href="https://github.com/geektousif" target="_blank" class="underline">Tousif</a>. &copy; <%= Time.current.year %> 
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-white border-b py-4 px-5 shadow-sm">
  <div class="container mx-auto flex justify-between items-center">
     

     
     <% if user_signed_in? %>
     <%= link_to "#{current_user.type.capitalize}'s Portal", send("#{current_user.type.downcase}s_root_path") , class: "font-bold text-blue-600 text-xl" %>

      <div class="flex gap-6 items-center">
        <span class="text-gray-700">Hello <strong><%= current_user.full_name %></strong></span> | 
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: " cursor-pointer inline-flex items-center px-4 py-2 bg-red-600 text-white text-sm font-medium rounded-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500" %>
      </div>
     <% else %>
     <%= link_to "Clinic Portal", root_path, class: "font-bold text-blue-600 text-xl cursor-pointer " %>
       <%= link_to "Login", new_user_session_path, class: "text-blue-600 hover:underline cursor-pointer " %>
     <% end %>
  </div>
</nav>
 